# Generated by Django 4.2.6 on 2023-10-18 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('image', models.FileField(blank=True, null=True, upload_to='contest_thumbnail/')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'active'), ('ended', 'ended')], max_length=250)),
                ('winner', models.CharField(blank=True, max_length=250, null=True)),
                ('winner_image', models.FileField(blank=True, null=True, upload_to='winner_image/')),
                ('slug', models.CharField(help_text='this-is-slug', max_length=250)),
                ('availble_seat', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitLogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='file/')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile')),
            ],
        ),
        migrations.CreateModel(
            name='JoinContest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile')),
            ],
        ),
    ]
