# Generated by Django 4.2.6 on 2023-10-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_results_banner_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.FileField(blank=True, null=True, upload_to='about/')),
                ('heading', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
